import Head from "next/head";
import Navbar from "../components/nav/Navbar";
import Footer from "../components/footer/Footer";

import HomeComp from "../components/pageComp/Home";
import OurMission from "../components/pageComp/OurMission";
import OurTeam from "../components/pageComp/OurTeam";
import Testimonials from "../components/pageComp/Testimonials";
import Contact from "../components/pageComp/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <HomeComp />
        <OurMission />
        <OurTeam />
        <Testimonials />
        <Contact />
      </main>
    </>
  );
}
